language: python
python: 3.7
dist: xenial

install:
  - pip install -r requirements.txt

script: 
  - pytest

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: urpx
  on:
    branch: master