language: python
python: 3.7
virtualenv:
  system_site_packages: true

install:
  - pip install -r requirements.txt

script: 
  - pytest

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  on:
    branch: master